### ISSUE TITLE
test thumbnail on phone and see if there's a way to detect the platform

### ISSUE THREAD

**Issue by christinechengubc** [christinechengubc/WargamersApp#78]
The BGG API returns 2 image sources for each game. One is a high-resolution (supposedly) image, the other is a thumbnail. Currently we are using the high-resolution image.

Please take a look to see if the thumbnail might look ok on the phone, and if it does maybe it's better to use that so it takes less data from the app user.

Thumbnails look too small on the website. Please also take a look if it is possible to detect the platform that the user is using to view the app so we can dynamically adjust whether to show the image or the thumbnail.

There is also the issue of the high-resolution image being too big when shown on the website. Will make another issue for that but it's a problem we should consider. Maybe we will need to redesign how our cards work (maybe have the image on the left, words on the right?).

**Comment by terbb** [comment]
It is possible to detect the platform and display either the thumbnail or the image. Here are my thoughts after testing the thumbnail on the phone:

1. The thumbnail looks a little too blurry on the phone to be the image of the card. We probably have to look into styling it another way to make it look a bit better. The web version has a problem of stretching the cards out really large which could be an issue but I was thinking that if we could limit the web version to look like the mobile version (instead of letting it stretch so large) for now we could go with this alternative.
2. Alternatively we could compress and re-size the image ourself after receiving it from BGG into our desired size. This is a bit complicated though so I think we should look into the first way.

**Comment by christinechengubc** [comment]
Okay, created #91 for this.
